server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/angelfernandez27/backend2_microservices_project


eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka

